blog/models.py
from django.db import models

from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)#date for creation
    author = models.ForeignKey(User , on_delete=models.CASCADE)
    date_modified = models.DateTimeField(auto_now=True)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView, 
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Post

def home(request):
    context = {'posts' : Post.objects.all()}
    return render(request, 'blog/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 4


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')
        
        

class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['title', 'content', 'image']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content','image']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    context = {'title': 'About'}
    return render(request, 'blog/about.html', context)

# Create your views here.

blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}

    <style>
        
        .content-section {
            background: rgba(33, 26, 117, 0.227);
            padding: 20px 30px;
            border: 1px solid #dddddd;
            border-radius: 3px;
            margin-bottom: 20px;
            display: flex;
            flex-direction: row; 
        }
    
        .article-title {
            color: #fbf3f3;
        }
    
        a.article-title:hover {
            color: rgb(37, 82, 127);
            text-decoration: none;
        }
    
        .article-content {
            white-space: pre-line;
        }
    
        .article-img {
            height: 65px;
            width: 65px;
            margin-right: 16px;
        }
    
        .article-metadata {
            padding-bottom: 1px;
            margin-bottom: 4px;
            border-bottom: 1px solid #e3e3e3
        }
    
        .article-metadata a:hover {
            color: #f3ecec;
            text-decoration: none;
        }
        img {
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 5px;
            
        } 

        img:hover{
            box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);

        }
    </style>

    {% for post in posts %}

        <article class="media content-section">
            <img class='rounded-circle article-img' src="{{ post.author.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-white">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                {% if post.image %}
                    <img class="border-light img-fluid rounded " src="{{post.image.url}}">
                {% endif %}
                <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
        
    {% endfor %}
    {%if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-light mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-light mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-light mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-light mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}

    {% endif %}
    
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

    <style>
        
        .content-section {
            background: #ffffff;
            padding: 10px 20px;
            border: 1px solid #dddddd;
            border-radius: 3px;
            margin-bottom: 20px;
            display: flex;
            flex-direction: row;
            background-image: url("https://t4.ftcdn.net/jpg/01/28/98/53/360_F_128985367_mNdX0b56w6OcgiyUDnZwukpK1bkpfWwI.jpg");

        }
    
        .article-title {
            color: #ffffff;
        }
    
        a.article-title:hover {
            color: #eef0f2;
            text-decoration: none;
        }
    
        .article-content {
            white-space: pre-line;
        }
    
        .article-img {
            height: 65px;
            width: 65px;
            margin-right: 16px;
        }
    
        .article-metadata {
            padding-bottom: 1px;
            margin-bottom: 4px;
            border-bottom: 1px solid #e3e3e3
        }
    
        .article-metadata a:hover {
            color: #f7f2f2;
            text-decoration: none;
        }
    </style>
    
    <article class="media content-section">
        <img class='rounded-circle article-img' src="{{ object.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
                <small class="text-white">{{ object.date_posted|date:"F d, Y" }}</small>
                {% if object.author == user %}
                    
                    <div>
                        
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
                    </div>

                {% endif %}
            </div>
            <img class="img-fluid " src="{{ object.image.url }}" alt="image for {{object.title}}" >
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
        </div>
    </article>
        
    
{% endblock content %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">

    .container{
        margin-left: 10px;
        margin-top: -10px;
    }
    form{
        background-image: url("https://t4.ftcdn.net/jpg/01/28/98/53/360_F_128985367_mNdX0b56w6OcgiyUDnZwukpK1bkpfWwI.jpg");

    }
    strong{
        color: white;
    }
    
</style>

<div class="container">
    <form method="POST" class="form-control" enctype="multipart/form-data">{% csrf_token %}
        <fieldset class="form-group">
            <strong><legend class="border-bottom mb-4 text-light ">Blog Post</legend></strong>

                <strong>{{form.title.label_tag}}</strong><br>
                {{form.title}}<br><br>
                <strong>{{form.content.label_tag}}</strong><br>
                {{form.content}}
                <div class="form-group pt-2">
					<label for="id_image" class="text-light">Image: </label>
					<input  class="text-light" type="file" name="image" id="id_image" accept="image/*" required>
				</div>
                
        </fieldset>
        <div class="form-group pt-3 pb-3">
            <button type="submit" class="btn btn-primary">Post</button>
        </div>

    </form>
    
</div>

{% endblock content %}

blog/templates/blog/user_posts.html
{% extends 'base.html' %}

{% block content %}

    <style>
        
        .content-section {
            background: #ffffff;
            padding: 20px 30px;
            border: 1px solid #dddddd;
            border-radius: 3px;
            margin-bottom: 20px;
            display: flex;
            flex-direction: row; 
            background-image: url("https://t4.ftcdn.net/jpg/01/28/98/53/360_F_128985367_mNdX0b56w6OcgiyUDnZwukpK1bkpfWwI.jpg");

        }
    
        .article-title {
            color: #f8f7f7;
        }
    
        a.article-title:hover {
            color: #428bca;
            text-decoration: none;
        }
    
        .article-content {
            white-space: pre-line;
        }
    
        .article-img {
            height: 65px;
            width: 65px;
            margin-right: 16px;
        }
    
        .article-metadata {
            padding-bottom: 1px;
            margin-bottom: 4px;
            border-bottom: 1px solid #e3e3e3
        }
    
        .article-metadata a:hover {
            color: #333;
            text-decoration: none;
        }
    </style>

    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>

    {% for post in posts %}

        <article class="media content-section">
            <img class='rounded-circle article-img' src="{{ post.author.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="px-2 text-light">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
        
    {% endfor %}
    {%if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
    
{% endblock content %}